# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kajabi < Formula
  desc "The Kajabi CLI"
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_Darwin_arm64.tar.gz"
      sha256 "1b7fafd03ab99d2db863a0af119890824325f0b67823ac962cb35004fbdfd645"

      def install
        bin.install "kajabi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_Darwin_x86_64.tar.gz"
      sha256 "3dfa725915283169cd319731b6c218a1d1990edf73be5ab3f75e66ce21a101ae"

      def install
        bin.install "kajabi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_Linux_arm64.tar.gz"
      sha256 "640473ad21ce4f8d84801528b92d2b11c51ee042d49d68ba232483ce48b3aa4f"

      def install
        bin.install "kajabi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_Linux_x86_64.tar.gz"
      sha256 "ff644ca3281d1e0aa614d9058228243b79b3bde19de1b032b1a4eb315d7445f5"

      def install
        bin.install "kajabi"
      end
    end
  end
end
