# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kajabi < Formula
  desc "The Kajabi CLI"
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_0.0.5_Darwin_arm64.tar.gz"
      sha256 "7d42811516457e8e64ca82f4545dbfa7282662f537c89115c668729a3d2d8fb8"

      def install
        bin.install "kajabi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "f67014d20f0ad5249d86c49bc298742a59c668e1eda34b8705719bb64f2723ca"

      def install
        bin.install "kajabi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_0.0.5_Linux_arm64.tar.gz"
      sha256 "fcb81e6eee2711bd34fa9eff3b784dba095882b71537e59a8e9d08f0f7576dce"

      def install
        bin.install "kajabi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kajabi/kajabi-cli/releases/download/cli-0.0.5/kajabi_0.0.5_Linux_x86_64.tar.gz"
      sha256 "c2ca3cbc036a24a78c7faf03255a68ed49da053e94800e8871b6e0b0e714c0e5"

      def install
        bin.install "kajabi"
      end
    end
  end
end
